openapi: 3.0.0
info:
  title: Email API
  version: 1.0.0
  description: API for managing emails
servers:
  - url: http://localhost:3000/api/v1
paths:
  /api/v1/emails:
    get:
      summary: Get all emails
      responses:
        '200':
          description: A list of emails
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Email'
    post:
      summary: Send an email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Email'
      responses:
        '201':
          description: Email sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Email'
  /api/v1/emails/{id}:
    get:
      summary: Get an email by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID of the email to retrieve
      responses:
        '200':
          description: Email retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Email'
        '404':
          description: Email not found
    put:
      summary: Update an email by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID of the email to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Email'
      responses:
        '200':
          description: Email updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Email'
        '404':
          description: Email not found
    delete:
      summary: Delete an email by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID of the email to delete
      responses:
        '204':
          description: Email deleted successfully
        '404':
          description: Email not found

components:
  schemas:
    Email:
      type: object
      properties:
        id:
          type: string
        sender:
          type: string
          format: email
        recipient:
          type: string
          format: email
        subject:
          type: string
        body:
          type: string
        sentAt:
          type: string
          format: date-time

    Error:
      type: object
      properties:
        statusCode:
          type: integer
          format: int32
        message:
          type: string
        details:
          type: string
